name: "Bug Report"
description: "Create a report to help us improve"
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: |
        As a user, I expected ___ behavior but I am seeing ___
    validations:
      required: true

  - type: textarea
    id: bug-screenshots
    attributes:
      label: Screenshots
      description: Provide screenshots if applicable

  - type: textarea
    id: platform
    attributes:
      label: Platform
      description: |
        Please let us know which Operating System, Browser and Browser version you were using when the issue occurred.
      placeholder: |
        - Device Type: [e.g. Desktop, Mobile]
        - OS: [e.g. macOS, Windows, Linux, iOS, Android]
        - Browser: [e.g. Chrome, Safari, Firefox, React Native]
        - Version: [e.g. 91.1]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
