import type { NextPage } from "next";
import Head from "next/head";
import { AuthPanel } from "../components/auth-panel/auth-panel.component";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>3bean</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="grid grid-cols-2">
          <div className="h-screen flex justify-center items-center flex-col bg-gray-50">
            <AuthPanel />
          </div>
          <div>
            <img
              className="h-screen w-full object-cover opacity-80"
              src="https://images.unsplash.com/photo-1645181196184-3ae5bf3fc91d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1635&q=80"
              alt=""
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
